# Generated by Django 5.1.2 on 2024-11-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_profile_apellido_alter_profile_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='apellido',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
