# Generated by Django 5.1.2 on 2024-11-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
